server:
  port: 8073

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Zivin/springCloudConfig/
          searchPaths: respo
          username:
          password:

#中央服务管理配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/